deneme3/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using deneme3.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Hosting.Server;
using System;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.Drawing;
using System.Xml.Linq;
using System.Threading.Tasks;
using System.Security.Cryptography.X509Certificates;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Security.Cryptography;
using System.Text;

using deneme3.ViewModel;
using Microsoft.AspNetCore.Authorization;
using EntityLayer.Tables;
using static EntityLayer.Tables.Veli;
using static EntityLayer.Tables.Ogrenci;

namespace deneme3.Controllers
{
    public class OgrenciController : Controller
    {
        Context1 c = new Context1();
        OgrenciKayıtViewModel multi = new OgrenciKayıtViewModel();

        [HttpGet]
        public IActionResult Guncelle(int id)
        {
            multi.ogrenci = c.ogrencis.Find(id);
            multi.Anne = c.velis.FirstOrDefault(x => x.VelininTipi == VeliTipi.Anne && x.Ogrenci_Id == id);
            multi.Baba = c.velis.FirstOrDefault(x => x.VelininTipi == VeliTipi.Baba && x.Ogrenci_Id == id);

            var degerler = multi;

            degerler.ogrenci.OgrenciAdi = Decrypt(degerler.ogrenci.OgrenciAdi);
            degerler.ogrenci.OgrenciSoyad = Decrypt(degerler.ogrenci.OgrenciSoyad);

            return View(degerler);
        }

        [HttpPost]
        public async Task<IActionResult> Guncelle(IFormFile formFile, deneme3.ViewModel.OgrenciKayıtViewModel o)
        {
            var Ogrenci = c.ogrencis.Find(o.ogrenci.OgrenciNo);

            Ogrenci.OgrenciAdi = Encrypt(o.ogrenci.OgrenciAdi);
            Ogrenci.OgrenciSoyad = Encrypt(o.ogrenci.OgrenciSoyad);
            Ogrenci.TckimlikNo = o.ogrenci.TckimlikNo;
            Ogrenci.CepNo = o.ogrenci.CepNo;
            Ogrenci.Email = o.ogrenci.Email;
            Ogrenci.StudentGender = o.ogrenci.StudentGender;
            Ogrenci.DogumTarihi = o.ogrenci.DogumTarihi;
            Ogrenci.KayitTarihi = o.ogrenci.KayitTarihi;

            if (formFile != null)
            { 
            var extent = Path.GetExtension(formFile.FileName);
            var randomName = ($"{Guid.NewGuid()}{extent}");
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", randomName);
            byte[] x;
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await formFile.CopyToAsync(stream);
            }
            using (var stream = new FileStream(path, FileMode.Open))
            {
                Image a = new Bitmap(stream);
                x = ImageToByte(a);


            }
                o.ogrenci.fotograf = x;
                Ogrenci.fotograf = o.ogrenci.fotograf;
            }


            var Anne = c.velis.FirstOrDefault(x => x.VelininTipi == VeliTipi.Anne && x.Ogrenci_Id == o.ogrenci.OgrenciNo);
            var Baba = c.velis.FirstOrDefault(x => x.VelininTipi == VeliTipi.Baba && x.Ogrenci_Id == o.ogrenci.OgrenciNo);

            Baba.TckimlikNo = o.Baba.TckimlikNo;
            Baba.Veli_Ad = o.Baba.Veli_Ad;
            Baba.Veli_Soyad = o.Baba.Veli_Soyad;
            Baba.VelininTipi = o.Baba.VelininTipi;
            Baba.Meslek = o.Baba.Meslek;
            Baba.Eposta = o.Baba.Eposta;
            Baba.Cepno = o.Baba.Cepno;

            Anne.TckimlikNo = o.Anne.TckimlikNo;
            Anne.Veli_Ad = o.Anne.Veli_Ad;
            Anne.Veli_Soyad = o.Anne.Veli_Soyad;
            Anne.VelininTipi = o.Anne.VelininTipi;
            Anne.Meslek = o.Anne.Meslek;
            Anne.Eposta = o.Anne.Eposta;
            Anne.Cepno = o.Anne.Cepno;

            c.SaveChanges();
            return RedirectToAction("Index");
        }

        // [Authorize] gerek kalmadı
        public IActionResult Index()
        {
            var degerler = c.ogrencis.ToList();

            
            foreach (var x in degerler)
            { 

            var cozum = x.OgrenciAdi;
            var cozum2 =x.OgrenciSoyad;

            x.CozulmusOgrenciAdi = Decrypt(cozum);
            x.CozulmusOgrenciSoyad = Decrypt(cozum2);

            }
            

            return View(degerler);
        }

        [HttpGet]
        public IActionResult YeniDepartman()
        {

            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> YeniDepartman(IFormFile formFile, deneme3.ViewModel.OgrenciKayıtViewModel o) 
        {

                    if (formFile != null) 
                    { 
                        var extent = Path.GetExtension(formFile.FileName);
                        var randomName = ($"{Guid.NewGuid()}{extent}");
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", randomName);
                        byte[] x;
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                        }
                        using (var stream = new FileStream(path, FileMode.Open))
                        {
                            Image a = new Bitmap(stream);
                            x = ImageToByte(a);
                        }
                            o.ogrenci.fotograf = x;
                    }


                    else if (formFile == null && o.ogrenci.StudentGender == Gender.Kadin)
                    {
                        byte[] x;

                        Image a = new Bitmap("wwwroot/Graphics/woman.png");
                        x = ImageToByte(a);
                      
                        o.ogrenci.fotograf = x;
                    }


                    else if (formFile == null && o.ogrenci.StudentGender == Gender.Erkek)
                    {
                        byte[] x;

                        Image a = new Bitmap("wwwroot/Graphics/man.png");
                        x = ImageToByte(a);
                      
                        o.ogrenci.fotograf = x;
                    }


                    o.ogrenci.OgrenciAdi = Encrypt(o.ogrenci.OgrenciAdi);
                    o.ogrenci.OgrenciSoyad = Encrypt(o.ogrenci.OgrenciSoyad);                 

                    o.Baba.Ogrenci = o.ogrenci;
                    o.Anne.Ogrenci = o.ogrenci;

                    c.velis.Add(o.Baba);
                    c.velis.Add(o.Anne);
                    c.ogrencis.Add(o.ogrenci);

                    c.SaveChanges();
                    return RedirectToAction("Index");
        }

        public static byte[] ImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])converter.ConvertTo(img, typeof(byte[]));
        }
        public static Image ByteToImage(byte[] img)
        {
            Image x = (Bitmap)((new ImageConverter()).ConvertFrom(img));
            return x;
        }

        public ContentResult OgrenciDurumGetir(int id)
        {
            var Ogrenci = c.ogrencis.Find(id);
            if (Ogrenci.Durum == true)
            {
                return Content("<script> alert('Ogrenciyi Pasife Alıyorsunuz') </script>");
            }

            else
            {
                return Content("<script> alert('Ogrenciyi Aktife Alıyorsunuz') </script>");
            }
        }

        public IActionResult OgrenciDurumDegistir(int id)
        {
            var Ogrenci = c.ogrencis.Find(id);


            if (Ogrenci.Durum == true)
            {
                Ogrenci.Durum = false;
            }

            else
            {
                Ogrenci.Durum = true;
            }


            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult PasifeAl(int id)
        {
            var Ogrenci=c.ogrencis.Find(id);
            Ogrenci.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult AktifeAl(int id)
        {
            var Ogrenci = c.ogrencis.Find(id);
            Ogrenci.Durum = true;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult OgrenciGetir()
        {
           
            return View();
        }
        [HttpPost]
        public IActionResult OgrenciGetir(EntityLayer.Tables.Ogrenci o)
        {
            var degerler = c.ogrencis.Find(o.OgrenciNo);
            
            return View("OgrenciGoster",degerler);

        }
        
        public IActionResult TanımlıOgrenciGetir12()
        {
            var query = c.ogrencis.Where(s => s.Cinsiyet == "e"&& s.Durum==true).ToList();

            return View(query);

        }

        [Authorize(Roles ="B")]
        public IActionResult OgrenciDetay(int id)
        {
            var degerler = c.ogrencis.Find(id);
            //var degerler = c.ogrencis.FirstOrDefault(x => x.OgrenciNo == id);

            degerler.CozulmusOgrenciAdi = Decrypt(degerler.OgrenciAdi);
            degerler.CozulmusOgrenciSoyad = Decrypt(degerler.OgrenciSoyad);

            return View(degerler);

        }

        private string Encrypt(string clearText)
        {
            string encryptionKey = "MAKV2SPBNI99212";
            byte[] clearBytes = Encoding.Unicode.GetBytes(clearText);
            using (Aes encryptor = Aes.Create())
            {
                Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(encryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                encryptor.Key = pdb.GetBytes(32);
                encryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {

deneme3/Views/Ogrenci/Guncelle.cshtml
@using deneme3.ViewModel;
@using System.Buffers;
@model OgrenciKayıtViewModel;

@{
    ViewData["Title"] = "Öğrenci Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    <link rel="stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
        integrity = "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin = "anonymous" >
</script>

@section scripts
    {
    <script src="~/scripts-jquery/jquery-ui-1.13.2.min.js"></script>

    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                dateFormat: "dd-mm-yy",
                changemonth: true,
                changeyear: true
            });
        });
    </script>

}

<link href="~/content-jquery/themes/base/datepicker.css" rel="stylesheet" />


<head>
    <style>
        #example1 {
            box-sizing: content-box;
            width: 200px;
            height: 250px;
            padding: 50px;
            border: 2px solid green;
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        #example2 {
            box-sizing: content-box;
            width: 200px;
            height: 20px;
            padding: 20px;
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>


<form method="post" asp-controller="Ogrenci" enctype="multipart/form-data" asp-action="Guncelle">

    <fieldset class="form-group border border-success p-4" id="fieldddstyle" style="margin-top: 10px;">
        <legend class="w-auto px-2">Öğrenci Bilgileri</legend>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(x=>x.ogrenci.OgrenciNo)
                    @Html.TextBoxFor(x=>x.ogrenci.OgrenciNo,new{@class="form-control"})
                    @Html.LabelFor(x=>x.ogrenci.TckimlikNo)
                    @Html.TextBoxFor(x=>x.ogrenci.TckimlikNo,new{@class="form-control"})
                    @Html.LabelFor(x=>x.ogrenci.OgrenciAdi)
                    @Html.TextBoxFor(x=>x.ogrenci.OgrenciAdi,new{@class="form-control"})
                    @Html.LabelFor(x=>x.ogrenci.OgrenciSoyad)
                    @Html.TextBoxFor(x=>x.ogrenci.OgrenciSoyad,new{@class="form-control"})
                    @Html.LabelFor(x=>x.ogrenci.CepNo)
                    @Html.TextBoxFor(x=>x.ogrenci.CepNo,new{@class="form-control"})
                    @Html.LabelFor(x=>x.ogrenci.Email)
                    @Html.TextBoxFor(x=>x.ogrenci.Email,new{@class="form-control"})
                    <!--Cinsiyet-->
                    <label asp-for="ogrenci.StudentGender" class="control-label"></label>
                    <select asp-for="ogrenci.StudentGender"
                            class="form-control"
                            asp-items="Html.GetEnumSelectList<EntityLayer.Tables.Ogrenci.Gender>()">
                        <option>Cinsiyet</option>
                    </select>
                    <!--Cinsiyet-->
                    <!--Dogum Tarihi-->
                    @Html.LabelFor(x=>x.ogrenci.DogumTarihi)
                    <br/>
                    @Html.EditorFor(x=>x.ogrenci.DogumTarihi,new{@class="datepicker"})
                    <br/>
                    <!--Dogum Tarihi-->
                    <!--Kayit Tarihi-->
                    @Html.LabelFor(x=>x.ogrenci.KayitTarihi)
                    <br/>
                    @Html.EditorFor(x=>x.ogrenci.KayitTarihi,new{@class="datepicker"})
                    <br/>
                    <!--Kayit Tarihi-->
                </div>
            </div>

            <div class="col-md-6">
                <div class="center">
                    <div class="form-group">

                        <div id="example1">
                            <label for="formFile" class="form-label">Fotoğraf Yükleme <br> Alanı </label>
                        </div>

                        <div id="example2">
                            <input type="file" name="formFile" class="form-control-file" id="exampleFormControlFile1">
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </fieldset>

    <fieldset class="form-group border border-success p-4">
        <legend class="w-auto px-2">Baba Bilgileri</legend>
        <div class="form-group">
            <!--Veli Tipi-->
            <label asp-for="Baba.VelininTipi" class="control-label"></label>
            <select asp-for="Baba.VelininTipi"
                    class="form-control"
                    asp-items="Html.GetEnumSelectList<EntityLayer.Tables.Veli.VeliTipi>()">
                <option>Veli Tipi</option>
            </select>
            <!--Veli Tipi-->
            @Html.LabelFor(x=>x.Baba.TckimlikNo)
            @Html.TextBoxFor(x=>x.Baba.TckimlikNo,new{@class="form-control"})
            @Html.LabelFor(x=>x.Baba.Veli_Ad)
            @Html.TextBoxFor(x=>x.Baba.Veli_Ad,new{@class="form-control"})
            @Html.LabelFor(x=>x.Baba.Veli_Soyad)
            @Html.TextBoxFor(x=>x.Baba.Veli_Soyad,new{@class="form-control"})
            @Html.LabelFor(x=>x.Baba.Meslek)
            @Html.TextBoxFor(x=>x.Baba.Meslek,new{@class="form-control"})
            @Html.LabelFor(x=>x.Baba.Eposta)
            @Html.TextBoxFor(x=>x.Baba.Eposta,new{@class="form-control"})
            @Html.LabelFor(x=>x.Baba.Cepno)
            @Html.TextBoxFor(x=>x.Baba.Cepno,new{@class="form-control"})
        </div>
    </fieldset>

    <fieldset class="form-group border border-success p-4">
        <legend class="w-auto px-2">Anne Bilgileri</legend>
        <div class="form-group">
            <!--Veli Tipi-->
            <label asp-for="Anne.VelininTipi" class="control-label"></label>
            <select asp-for="Anne.VelininTipi"
                    class="form-control"
                    asp-items="Html.GetEnumSelectList<EntityLayer.Tables.Veli.VeliTipi>()">
                <option>Veli Tipi</option>
            </select>
            <!--Veli Tipi-->
            @Html.LabelFor(x=>x.Anne.TckimlikNo)
            @Html.TextBoxFor(x=>x.Anne.TckimlikNo,new{@class="form-control"})
            @Html.LabelFor(x=>x.Anne.Veli_Ad)
            @Html.TextBoxFor(x=>x.Anne.Veli_Ad,new{@class="form-control"})
            @Html.LabelFor(x=>x.Anne.Veli_Soyad)
            @Html.TextBoxFor(x=>x.Anne.Veli_Soyad,new{@class="form-control"})
            @Html.LabelFor(x=>x.Anne.Meslek)
            @Html.TextBoxFor(x=>x.Anne.Meslek,new{@class="form-control"})
            @Html.LabelFor(x=>x.Anne.Eposta)
            @Html.TextBoxFor(x=>x.Anne.Eposta,new{@class="form-control"})
            @Html.LabelFor(x=>x.Anne.Cepno)
            @Html.TextBoxFor(x=>x.Anne.Cepno,new{@class="form-control"})
        </div>
    </fieldset>

    <button class="btn btn-info">Güncelle</button>

</form>

deneme3/Views/Ogrenci/Index.cshtml
@using EntityLayer.Tables;
@model List<Ogrenci>;
@using System.Web;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="sweetalert2.all.min.js"></script>
</head>

<body>

<h1>Öğrenci Bul</h1>
<label>Öğrenci Bul</label>
<input type="text" id="ad_search_query" style="width:295px">&nbsp;
<input type="button" value="Bul" class="p-userButton" onClick="OgrenciDetaylar(document.getElementById('ad_search_query').value);" />

<h1>Öğrenci Listesi</h1>


<script>
    function myFunction(id) 
    {
        alert("Öğrencinin Durumunu Değiştirmek Üzeresiniz!");
        window.location.href = '@Url.Action("OgrenciDurumDegistir", "Ogrenci" , new {id = "ID"})'.replace("ID", parseInt(id));       
    }

    function OgrenciDetaylar(id) 
    {
        alert(id + " Numaralı öğrencinin detaylarına yönlendirileceksiniz.");
        window.location.href = '@Url.Action("OgrenciDetay", "Ogrenci" , new {id = "ID"})'.replace("ID", parseInt(id));
    }

    /*
    function OgrenciGuncelle(id) 
    {
        alert(id + " Numaralı öğrencinin bilgilerini güncelleyeceksiniz. ");
        window.location.href = 'Url.Action("Guncelle", "Ogrenci" , new {id = "ID"})'.replace("ID", parseInt(id));
    }
    */

    
    function OgrenciGuncelle(id) 
    {
            Swal.fire({
                title: 'Emin Misiniz ?',
                text: id + " Numaralı öğrencinin bilgilerini güncelleyeceksiniz. ",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Evet',
                cancelButtonText: "Hayır"
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        timer: 4000,
                        title: 'Bilgiler',
                        text: "Öğrenci Bilgilerine Yönlendiriliyorsunuz",
                        icon: "success",
                        showCancelButton: false,
                        showConfirmButton: false,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                    })

                    window.location.href = '@Url.Action("Guncelle", "Ogrenci" , new {id = "ID"})'.replace("ID", parseInt(id));
                }
            })
    }
</script>

<div style="overflow-x:auto;">

<table class="table table-bordered table table-striped">
    <thead class="thead-dark">
    <tr>
        <th class="text-center">Öğrenci<br>Fotoğraf</th> 
        <th class="text-center">Öğrenci<br>Numarası</th>
        <th class="text-center">Öğrenci<br>Adı</th>
        <th class="text-center">Öğrenci<br>Soyadı</th>
        <th class="text-center">Kimlik<br>Numarası</th>
        <th class="text-center">Öğrenci<br>Cinsiyet</th>
        <th class="text-center">Öğrenci<br>Email</th>
        <th class="text-center">Öğrenci<br>Düzenle</th>
        <th class="text-center">Öğrenci<br>Durumu</th>
        <th class="text-center">Kayıt<br>Tarihi</th>
        <th class="text-center">Doğum<br>Tarihi</th>
        <th class="text-center">Öğrenci<br>Yaş</th>
        <th class="text-center">Öğrenci<br>Detay</th>
    </tr>
    </thead>

    @foreach (var x in Model)
    {

        <tr>
            <td><img onerror="this.src = 'default.jpg'" width="50" height="50" src="@String.Format("data:image/png;base64,{0}",Convert.ToBase64String(@x.fotograf))"></td>
            <td>@x.OgrenciNo</td>

            <td>@x.CozulmusOgrenciAdi</td>

            <td>@x.CozulmusOgrenciSoyad</td>

            <td>@x.TckimlikNo</td>
            <td>@x.StudentGender</td>
            <td>@x.Email</td>

            <td>
                <span>
                    <a onclick="OgrenciGuncelle(@x.OgrenciNo)" class="btn btn-danger">Düzenle</a>
                </span>
            </td>

            <td>

            @if (x.Durum == true) 
            { 
                    <label class="switch">
                        <input id="Durum" type="checkbox" checked onclick="myFunction(@x.OgrenciNo)">
                        <span class="slider round"></span>
                    </label>
            }
            

            @if (x.Durum == false)
            {
                    <label class="switch">
                        <input id="Durum" type="checkbox" onclick="myFunction(@x.OgrenciNo)">
                        <span class="slider round"></span>
                    </label>
            }


                @if (x.Durum == true) { <label>Aktif</label> } else { <label>Pasif</label>  }

                <!-- 
                <a href="/Ogrenci/PasifeAl/@x.OgrenciNo" class=" btn btn-danger">PasifeAl</a>
                <a href="/Ogrenci/AktifeAl/@x.OgrenciNo" class=" btn btn-danger">AktifeAl</a>
                -->
                
            </td>

            <td>@x.KayitTarihi</td>

            <td>@x.DogumTarihi</td>


            <td>
                <!-- age calculation-->
                @{
                    var birthday = @x.DogumTarihi;
                    int age = (int)((DateTime.Now - birthday).TotalDays / 365.242199);
                    @x.Yas = age;
                }
                <!-- age calculation-->
                @x.Yas
            </td>

            <td>
                <span> 
                <a href="/Ogrenci/OgrenciDetay/@x.OgrenciNo" class=" btn btn-danger">Detay Göster</a>
                <a href="/Ogrenci/OgrenciDetay/@x.OgrenciNo" class=" btn btn-primary">Veli Göster</a>
                </span>
            </td>

        </tr>
    }

</table>

</div>

<style>

    .table-striped > tbody > tr:nth-child(odd) > td,
    .table-striped > tbody > tr:nth-child(odd) > th 
    {
        background-color: #FFF0F5;
    }

    .table-striped > tbody > tr:nth-child(even) > td,
    .table-striped > tbody > tr:nth-child(even) > th 
    {
        background-color: #F0FFF0;
    }

    .table-striped > tbody > tr > td,
    .table-striped > tbody > tr > th,
    .table-bordered > tbody > tr > td,
    .table-bordered > tbody > tr > th 
    {
        border: 1px solid black;
    }

</style>

<a href="/Ogrenci/YeniDepartman" class=" btn btn-danger" >Öğrenci Ekle</a>
<a href="/Ogrenci/OgrenciGetir" class=" btn btn-danger">Öğrenci Getir</a>
<a href="/Ogrenci/TanımlıOgrenciGetir12" class=" btn btn-danger">Tanımlı Öğrenci Getir</a>
<a href="/Report/Print" class=" btn btn-danger">Raporlama</a>

</body>

@section Scripts
    {
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        .slider.round {
            border-radius: 34px;
        }

            .slider.round:before {
                border-radius: 50%;
            }
    </style>
}

deneme3/Views/Ogrenci/OgrenciGetir.cshtml
@model EntityLayer.Tables.Ogrenci;
@{
    ViewData["Title"] = "OgrenciGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Öğrenci Getir</h1>

<form class="form-group" method="post">


    <label>Öğrenci No</label>
    @Html.TextBoxFor(x=>x.OgrenciNo,new{@class="form-control"})

    <div class="form-group">
        <button class="btn btn-info" style="margin: 10px 10px 10px 0px;">Ekle</button>
    </div>

</form>

deneme3/Views/Ogrenci/OgrenciGoster.cshtml
@using EntityLayer.Tables;
@model EntityLayer.Tables.Ogrenci
@{
    ViewData["Title"] = "OgrenciGoster";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Öğrenci Göster</h1>

<table class=" table table-bordered">
    <tr>
        <th>TckimlikNo</th>
        <th>OgrenciNo</th>
        <th>Cinsiyet</th>
        <th>OgrenciSoyad</th>
        <th>Ekle</th>
        <th>Durum</th>
    </tr>

       <tr>
            <td>@Model.TckimlikNo</td>
            <td>@Model.OgrenciNo</td>
            <td>@Model.Cinsiyet</td>
            <td>@Model.OgrenciSoyad</td>
            <td>


            </td>


        </tr>
    

   
</table>

deneme3/Views/Ogrenci/TanımlıOgrenciGetir12.cshtml
@using EntityLayer.Tables
@{
    ViewData["Title"] = "TanımlıOgrenciGetir12";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tanımlı Öğrenci Getir</h1>

<table class=" table table-bordered">
    <tr>
        <th>Öğrenci Numarası</th>
        <th>Öğrenci Ad</th>
        <th>Öğrenci Soyad</th>
        <th>Kimlik Numarası</th>
        <th>Cinsiyet</th>
        <th>Durum</th>
    </tr>
    @foreach (var x in Model)
    {

        <tr>
            <td>@x.OgrenciNo</td>
            <th>@x.OgrenciAdi</th>
            <td>@x.OgrenciSoyad</td>
            <td>@x.TckimlikNo</td>
            <td>@x.Cinsiyet</td>
            <td>@x.Durum</td>
        </tr>
    }
</table>