deneme3/Controllers/FaturaController.cs
using deneme3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace deneme3.Controllers
{
    public class FaturaController : Controller
    {
        Context1 c = new Context1();
        public IActionResult Index()
        {
            var degerler = c.fatura.ToList();
            return View(degerler);
        }
        

        [HttpGet]
        public IActionResult FaturaEkle()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult FaturaEkle(EntityLayer.Tables.Fatura o)
        {
            c.fatura.Add(o);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult FaturaSorgu(string fatura_ad, string fatura_soyad)
        {
            var adin = fatura_ad;
            var soyadin = fatura_soyad;

            var query = c.fatura.Where(s => s.Birey_Adi == fatura_ad && s.Birey_Soyadi == fatura_soyad).ToList();

            return View(query);
        }

        public IActionResult FaturaDetay(int id)
        {
            var degerler = c.fatura.Find(id);

            return View(degerler);

        }
    }
}

deneme3/Views/Fatura/FaturaDetay.cshtml
@using System.Security.Cryptography;
@using EntityLayer.Tables;
@using System.IO
@using System.Text
@model EntityLayer.Tables.Fatura;
@{
    ViewData["Title"] = "FaturaDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>

<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<body>


    <h1>Fatura Detayları</h1>

    <table class="table table-bordered table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Fatura Numarası</th>

                <th>Fatura Tipi</th>

                <th>Firma Adı</th>
                <th>Vergi Numarası</th>
                <th>Vergi Dairesi Adı</th>

                <th>Birey Adı</th>
                <th>Birey Soyadı</th>
                <th>Birey TC</th>

                <th>Seri No</th>
                <th>Sıra No</th>
                <th>Şube No</th>
                <th>İşlem No</th>
                <th>İşlem Tutarı</th>
                <th>Kdv Oranı</th>
                <th>Toplam Tutar</th>
                <th>Fatura Tarihi</th>
                <th>Onay Kodu</th>

                <th>Fatura Detay</th>
            </tr>
        </thead>

        <tr>
            <td>@Model.fatura_no</td>

            <td>@Model.Fatura_Tipi</td>

            <td>@Model.Firma_Adi</td>
            <td>@Model.Vergi_No</td>
            <td>@Model.Vergi_Dairesi_Adi</td>

            <td>@Model.Birey_Adi</td>
            <td>@Model.Birey_Soyadi</td>
            <td>@Model.Birey_Tc</td>


            <td>@Model.Seri_No</td>
            <td>@Model.Sıra_No</td>
            <td>@Model.Sube_No</td>
            <td>@Model.Islem_No</td>
            <td>@Model.Islem_Tutarı</td>
            <td>@Model.Kdv_Oranı</td>
            <td>@Model.Toplam_Tutar</td>
            <td>@Model.Fatura_Tarihi</td>
            <td>@Model.Onay_Kodu</td>
            <td>
                <span>
                    <a href="/Fatura/FaturaDetay/@Model.fatura_no" class="btn btn-danger">Fatura Detay</a>
                </span>
            </td>
        </tr>

    </table>


    <style>

        .table-striped > tbody > tr:nth-child(odd) > td,
        .table-striped > tbody > tr:nth-child(odd) > th {
            background-color: #FFF0F5;
        }

        .table-striped > tbody > tr:nth-child(even) > td,
        .table-striped > tbody > tr:nth-child(even) > th {
            background-color: #F0FFF0;
        }

        .table-striped > tbody > tr > td,
        .table-striped > tbody > tr > th,
        .table-bordered > tbody > tr > td,
        .table-bordered > tbody > tr > th {
            border: 1px solid black;
        }

    </style>

</body>
</html>

deneme3/Views/Fatura/FaturaEkle.cshtml
@using EntityLayer.Tables;
@model EntityLayer.Tables.Fatura;
@{
    ViewData["Title"] = "FaturaEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Fatura Ekle</h1>
<form class="form-group" method="post">

    <label>Fatura Numarası</label>
    @Html.TextBoxFor(x=>x.fatura_no,new{@class="form-control"})
    <label>Vergi Numarası</label>
    @Html.TextBoxFor(x=>x.Vergi_No,new{@class="form-control"})
    <label>Vergi Dairesi Adı</label>
    @Html.TextBoxFor(x=>x.Vergi_Dairesi_Adi,new{@class="form-control"})
    <label>Seri Numarası</label>
    @Html.TextBoxFor(x=>x.Seri_No,new{@class="form-control"})
    <label>Şube Numarası</label>
    @Html.TextBoxFor(x=>x.Sube_No,new{@class="form-control"})
    <label>İşlem Tutarı</label>
    @Html.TextBoxFor(x=>x.Islem_Tutarı,new{@class="form-control"})
    <label>Kdv Oranı</label>
    @Html.TextBoxFor(x=>x.Kdv_Oranı,new{@class="form-control"})
    <label>Toplam Tutar</label>
    @Html.TextBoxFor(x=>x.Toplam_Tutar,new{@class="form-control"})
    <label>İşlem Numarası</label>
    @Html.TextBoxFor(x=>x.Islem_No,new{@class="form-control"})
    <label>Onay Kodu</label>
    @Html.TextBoxFor(x=>x.Onay_Kodu,new{@class="form-control"})

    <div class="form-group">
        <button class="btn btn-info" style="margin: 10px 10px 10px 0px;">Ekle</button>
    </div>

</form>

deneme3/Views/Fatura/FaturaGoster.cshtml
@{
    ViewData["Title"] = "FaturaGoster";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>FaturaGoster</h1>

deneme3/Views/Fatura/FaturaSorgu.cshtml
@using System.Security.Cryptography;
@using EntityLayer.Tables;
@using System.IO
@using System.Text
@model List<Fatura>;
@{
    ViewData["Title"] = "FaturaDetay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html>

<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<body>


    <h1>Fatura Sorguları</h1>

<table class="table table-bordered table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Fatura Numarası</th>

        <th>Fatura Tipi</th>

        <th>Firma Adı</th>
        <th>Vergi Numarası</th>
        <th>Vergi Dairesi Adı</th>

        <th>Birey Adı</th>
        <th>Birey Soyadı</th>
        <th>Birey TC</th>

        <th>Seri No</th>
        <th>Sıra No</th>
        <th>Şube No</th>
        <th>İşlem No</th>
        <th>İşlem Tutarı</th>
        <th>Kdv Oranı</th>
        <th>Toplam Tutar</th>
        <th>Fatura Tarihi</th>
        <th>Onay Kodu</th>

        <th>Fatura Detay</th>
    </tr>
    </thead>

    @foreach (var x in Model)
    {

        <tr>
            <td>@x.fatura_no</td>

            <td>@x.Fatura_Tipi</td>

            <td>@x.Firma_Adi</td>
            <td>@x.Vergi_No</td>
            <td>@x.Vergi_Dairesi_Adi</td>

            <td>@x.Birey_Adi</td>
            <td>@x.Birey_Soyadi</td>
            <td>@x.Birey_Tc</td>


            <td>@x.Seri_No</td>
            <td>@x.Sıra_No</td>
            <td>@x.Sube_No</td>
            <td>@x.Islem_No</td>
            <td>@x.Islem_Tutarı</td>
            <td>@x.Kdv_Oranı</td>
            <td>@x.Toplam_Tutar</td>
            <td>@x.Fatura_Tarihi</td>
            <td>@x.Onay_Kodu</td>

            <td>
                <span>
                    <a href="/Fatura/FaturaDetay/@x.fatura_no" class="btn btn-danger">Fatura Detay</a>
                </span>
            </td>

        </tr>
    }

</table>

    <style>

        .table-striped > tbody > tr:nth-child(odd) > td,
        .table-striped > tbody > tr:nth-child(odd) > th {
            background-color: #FFF0F5;
        }

        .table-striped > tbody > tr:nth-child(even) > td,
        .table-striped > tbody > tr:nth-child(even) > th {
            background-color: #F0FFF0;
        }

        .table-striped > tbody > tr > td,
        .table-striped > tbody > tr > th,
        .table-bordered > tbody > tr > td,
        .table-bordered > tbody > tr > th {
            border: 1px solid black;
        }

    </style>

</body>
</html>

deneme3/Views/Fatura/Index.cshtml
@using EntityLayer.Tables;
@model List<Fatura>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Fatura Listesi</h1>

<label>Fatura Bul</label>
<label>Ad</label>
<input type="text" id="ad_search_query" style="width:295px">&nbsp;
<label>Soyad</label>
<input type="text" id="soyad_search_query" style="width:295px">&nbsp;
<input type="button" value="Bul" class="p-userButton" onClick="FaturaGet(document.getElementById('ad_search_query').value, document.getElementById('soyad_search_query').value);" />

<script>
    function FaturaGet(fatura_ad,fatura_soyad) 
    {
        alert(fatura_ad +" "+ fatura_soyad + " adlı kişinin faturasına yönlendirileceksiniz.")
        var url = '@Html.Raw(Url.Action("FaturaSorgu","Fatura", new { fatura_ad = "__fatura_ad__", fatura_soyad = "__fatura_soyad__"}))';
        var params = url.replace('__fatura_ad__', String(fatura_ad)).replace('__fatura_soyad__', String(fatura_soyad));
        window.location.href = params;
    }
</script>


<table class="table table-bordered table table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Fatura Numarası</th>

        <th>Fatura Tipi</th>

        <th>Firma Adı</th>
        <th>Vergi Numarası</th>
        <th>Vergi Dairesi Adı</th>

        <th>Birey Adı</th>
        <th>Birey Soyadı</th>
        <th>Birey TC</th>

        <th>Seri No</th>
        <th>Sıra No</th>
        <th>Şube No</th>
        <th>İşlem No</th>
        <th>İşlem Tutarı</th>
        <th>Kdv Oranı</th>
        <th>Toplam Tutar</th>
        <th>Fatura Tarihi</th>
        <th>Onay Kodu</th>

        <th>Fatura Detay</th>
    </tr>
    </thead>

    @foreach (var x in Model)
    {

        <tr>
            <td>@x.fatura_no</td>

            <td>@x.Fatura_Tipi</td>

            <td>@x.Firma_Adi</td>
            <td>@x.Vergi_No</td>
            <td>@x.Vergi_Dairesi_Adi</td>

            <td>@x.Birey_Adi</td>
            <td>@x.Birey_Soyadi</td>
            <td>@x.Birey_Tc</td>


            <td>@x.Seri_No</td>
            <td>@x.Sıra_No</td>
            <td>@x.Sube_No</td>
            <td>@x.Islem_No</td>
            <td>@x.Islem_Tutarı</td>
            <td>@x.Kdv_Oranı</td>
            <td>@x.Toplam_Tutar</td>
            <td>@x.Fatura_Tarihi</td>
            <td>@x.Onay_Kodu</td>

            <td>
                <span>
                    <a href="/Fatura/FaturaDetay/@x.fatura_no" class="btn btn-danger">Fatura Detay</a>
                </span>
            </td>


        </tr>
    }

</table>

<style>

    .table-striped > tbody > tr:nth-child(odd) > td,
    .table-striped > tbody > tr:nth-child(odd) > th {
        background-color: #FFF0F5;
    }

    .table-striped > tbody > tr:nth-child(even) > td,
    .table-striped > tbody > tr:nth-child(even) > th {
        background-color: #F0FFF0;
    }

    .table-striped > tbody > tr > td,
    .table-striped > tbody > tr > th,
    .table-bordered > tbody > tr > td,
    .table-bordered > tbody > tr > th {
        border: 1px solid black;
    }

</style>


<a href="/Fatura/FaturaEkle" class=" btn btn-danger">Fatura ekle</a>
<a href="/Fatura/FaturaGetir" class=" btn btn-danger">Fatura Getir</a>